### ISSUE TITLE
Reduce needed meta

### ISSUE THREAD

**Issue by mshd** [jlalmes/trpc-openapi#55]
Is your tool intented to be used as just an API endpoint? If so, would it be possible to reduce the meta openapi complexity, and just enable openapi for all routes?

```
openapi: {
        enabled: true,       //default from global settings
        method: "POST",      //default GET for query and POST for mutation
        path: "/auth/login", //defaults to TRPC route
        tag: "auth",
        summary: "Login as an existing user",
      },
```

**Comment by jlalmes** [comment]
I personally think it is best to require all of the above properties & not set any defaults so that it is clear to any developer the current state of any given procedure. Most importantly, I do not want endpoints to be exposed via a public API without it being explicitly defined. 

Let me know what you think - if you disagree, let's open a discussion and continue the conversation there.
