### ISSUE TITLE
The inferred type of 'default' cannot be named without a reference to  openApiDocument function

### ISSUE THREAD

**Issue by mshd** [jlalmes/trpc-openapi#57]
![Screenshot from 2022-07-09 20-37-36](https://user-images.githubusercontent.com/17379661/178106167-616660af-b61e-403a-bbe1-735dff7604d6.png)

	"message": "The inferred type of 'default' cannot be named without a reference to '.pnpm/next@12.2.0_beenoklgwfttvph5dgxj7na7aq/node_modules/next/types'. This is likely not portable. A type annotation is necessary.",

Sorry for spamming btw!

**Comment by jlalmes** [comment]
Hi @mshd, from a quick Google, it seems this issue is likely `pnpm` related. I have just created a repo using `pnpm`, however cannot reproduce this error. Could you share a reproduction (ideally with StackBlitz) so I can debug this?

**Comment by mshd** [comment]
Hm, seems to work now.

**Comment by esamattis** [comment]
I saw this error as well but the issue was missing `DOM` lib in tsconfig.json (`compilerOptions.lib`). The error was confusing because I had `skipLibCheck: true`. When I set it to `false` I was able to see `Cannot find name 'Response'` style errors which referenced the Fetch API Response class which is in the DOM lib in TS.
