### ISSUE TITLE
Typescript response (instead zod) to Openapi

### ISSUE THREAD

**Issue by mshd** [jlalmes/trpc-openapi#61]
In TRPC I only need to use zod (or yup) for the input, but the output type gets automatically passed on to the frontend without a need for zod.
I want to make an endpoint for a function that  already has a typed response. I would rather not have to rewrite all types into zod.

**Comment by jlalmes** [comment]
Unfortunately, _for now_ you are required to add a `zod` output schema for each endpoint because this is needed to generate the OpenAPI response body schema.

Fortunately, @sachinraja is working on a tool that will enable us to generate schemas from TS return types (https://github.com/sachinraja/trpc-snapshot) coming soon 🚀.

**Comment by sachinraja** [comment]
The repo is private because there's nothing usable yet (only a POC). I'm also focusing on tRPC v10 stuff at the moment.
